In [1]:
# 아래에 실습코드를 작성하고 결과를 확인합니다.
import numpy as np
import pandas as pd

In [5]:
# 아래에 실습코드를 작성하고 결과를 확인합니다.
df17 = pd.read_csv('C:/Users/User/Desktop/미니프로젝트5차_생활인구 4_5일차/data2017.csv', sep=',', index_col=0)
df17

,시간대구분,총생활인구수,남자0세부터9세생활인구수,남자10세부터14세생활인구수,남자15세부터19세생활인구수,남자20세부터24세생활인구수,남자25세부터29세생활인구수,남자30세부터34세생활인구수,남자35세부터39세생활인구수,남자40세부터44세생활인구수,...,여자25세부터29세생활인구수,여자30세부터34세생활인구수,여자35세부터39세생활인구수,여자40세부터44세생활인구수,여자45세부터49세생활인구수,여자50세부터54세생활인구수,여자55세부터59세생활인구수,여자60세부터64세생활인구수,여자65세부터69세생활인구수,여자70세이상생활인구수
기준일ID,,,,,,,,,,,,,,,,,,,,,
20170101,0,31535.2200,1945.4402,566.4588,631.5581,991.9184,1297.1287,1223.1529,1552.9448,1236.7535,...,1157.6661,1107.6781,1282.9235,1029.4360,998.0414,874.5643,1162.1547,1053.0477,964.3940,2025.4819
20170101,1,31188.9174,1930.4766,562.1018,625.2151,1030.6281,1307.7381,1183.0956,1491.5827,1236.8635,...,1120.0051,1102.5198,1271.8997,1027.2574,1038.7528,857.9100,1149.7532,1042.7411,919.0115,2062.2422
20170101,2,31240.4974,1921.1864,559.3965,658.7463,1058.7082,1311.9591,1186.2600,1537.3732,1211.8326,...,1103.1547,1112.4579,1282.9366,1027.8901,1020.0177,853.3890,1193.4472,1011.2073,889.9325,1960.1236
20170101,3,31442.4314,1946.4476,566.7525,649.0804,1057.9119,1324.2638,1202.1250,1521.2732,1232.8897,...,1116.2165,1102.0668,1260.8472,1007.6650,1042.9554,896.0038,1163.0355,1056.6428,891.9177,2060.1872
20170101,4,31922.7751,1953.7713,568.8845,623.2087,1063.2557,1342.9146,1209.2680,1556.0675,1282.1621,...,1187.5457,1120.2232,1281.2738,1064.0655,1045.2130,895.8336,1191.7017,1045.3362,874.4984,2038.6212
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20171231,19,38113.9642,2328.4174,677.9711,747.0057,1310.8254,1365.0662,1514.1769,1702.6725,1534.6734,...,1486.8736,1476.7567,1614.6091,1403.0718,1303.2542,1188.2181,1377.4488,1240.3537,1009.2761,2384.1143
20171231,20,37388.1990,2111.1139,614.6985,789.3426,1220.3156,1330.6476,1430.2718,1761.7189,1502.9735,...,1435.7299,1532.5202,1608.3678,1394.3794,1257.1747,1105.3676,1401.8941,1290.2562,991.1137,2406.1112
20171231,21,36784.5323,2153.8616,627.1453,782.7005,1245.7532,1265.5612,1406.7923,1829.3613,1531.2415,...,1365.5078,1422.4146,1616.7976,1323.6089,1217.1773,1100.1336,1406.2490,1285.2969,992.8191,2205.1798
20171231,22,37039.2231,2070.6344,602.9120,717.1471,1240.4565,1354.4798,1471.0552,1828.5542,1502.2804,...,1423.5042,1460.4424,1577.2544,1345.0946,1193.1667,1058.8461,1391.7570,1360.7727,996.2383,2265.4311
20171231,23,36359.7592,2403.6778,699.8851,744.5285,1227.6767,1242.8245,1300.4394,1847.6015,1468.8832,...,1187.1879,1423.0350,1503.0919,1392.7659,1135.7928,1069.8926,1402.9536,1186.3097,1038.9159,2217.9620